events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://hub-app:5000/;
        }

        location /lab1/login {
            proxy_pass http://lab1-go:8080/login;
        }

        location /lab1/verify {
            proxy_pass http://lab1-python:5000/verify;
        }

        location /lab2/wallet {
            proxy_pass http://lab2-python:5000/wallet;
        }

        location /lab2/buy {
            proxy_pass http://lab2-python:5000/buy;
        }

        location /lab3/wallet {
            proxy_pass http://lab3-perl:5000/wallet;
        }

        location /lab3/buy {
            proxy_pass http://lab3-perl:5000/buy;
        }

    }
}
